### ISSUE TITLE
DMA/INT OUT/IN

### ISSUE THREAD

**Issue by marketideas** [a2fpga/a2fpga_core#10]
Looking at the schematic, it doesn't look like DMA_OUT is tied to DMA_IN and same for INT_IN/OUT.  This breaks the rudimentary daisy chain if the card is put in any slot except slot 7.  Is there a design reason, and perhaps this should be documented so that folks know that any card(s) in higher slots may not work reliably with DMA and/or interupts.

**Comment by edanuff** [comment]
Hello, that's correct, the current boards don't support daisy chaining. We'll be documenting this and adding it to a later revision.
