### ISSUE TITLE
mb-audit

### ISSUE THREAD

**Issue by DFL1973** [a2fpga/a2fpga_core#11]
Is the emulated mockingboard passing on the mb-audit tests? 
https://github.com/tomcw/mb-audit

**Comment by jewettg** [comment]
I updated my A2N20 with the latest release:  `a2n20v2-10-12-2024-MB4.fs`.  Here is the successful output from the reprogramming.    I then ran the latest undead from disk image, and it would not detect the Mockingboard.   Is there something else I need to do?

Is there a good way to test MB functionality?  Debug methods?   I am going to see if I can find other disk images to help me test or see if this is working outside of Undead.

```
❯ openfpgaloader -b tangnano20k -f a2n20v2-10-12-2024-MB4.fs
empty
write to flash
Jtag frequency : requested 6.00MHz   -> real 6.00MHz
Parse file Parse a2n20v2-10-12-2024-MB4.fs:
Done
DONE
after program flash: displayReadReg 00006020
	Memory Erase
	Done Final
	Security Final
Erase SRAM DONE
Jtag probe limited to %d MHz6000000
Jtag frequency : requested 10.00MHz  -> real 6.00MHz
Detected: Winbond W25Q64 128 sectors size: 64Mb
Detected: Winbond W25Q64 128 sectors size: 64Mb
RDSR : 00
WIP  : 0
WEL  : 0
BP   : 0
TB   : 0
SRWD : 0
00000000 00000000 00000000 00
Erasing: [==================================================] 100.00%
Done
Writing: [==================================================] 100.00%
Done
```

**Comment by edanuff** [comment]
The mockingboard does not currently pass mbaudit tests.  We're still working on figuring out why.

**Comment by jewettg** [comment]
**I do want to apologize.**  After reading more documentation, I found I had to disable the mouse support (by marking slot 4 as "Your Card") on the Apple //gs.   All is well and Mocking board is detected and working!  It was even detected and working with other software as well!

**Comment by edanuff** [comment]
#22

**Comment by jewettg** [comment]
AWESOME!!   Thank you!   Will try it out soon!

**Comment by edanuff** [comment]
There will be a new release this weekend
