### ISSUE TITLE
Mouse

### ISSUE THREAD

**Issue by SalvadorCastello** [a2fpga/a2fpga_core#12]
Do you think you can add Mouse support to the firmware?
To act as an Apple Mouse card, those cards are difficult to find.

Thanks

**Comment by edanuff** [comment]
Not on the current version of the card since the USB port is device only for connecting to a PC.  We intend to do a future version that has a second USB host port that could be used for a mouse.

**Comment by JustDre** [comment]
Although I haven't tried this just yet, there is a project by the author of snestang that allows the USB port to act as a host https://github.com/nand2mario/usb_hid_host

**Comment by edanuff** [comment]
Yes, going to use something similar. The current board design has all the physical pins assigned right now although there are some workarounds for that.
