### ISSUE TITLE
CPLD

### ISSUE THREAD

**Issue by DFL1973** [a2fpga/a2fpga_core#9]
Is the CPLD code available?

**Comment by buserror** [comment]
No, I asked on slack. No board or CPLD, so this is basically a closed source project, it's a shame really. I don't see why anyone would contribute PR's to a project like this, unless perhaps they get a share of the profits from selling cards? Dunno, not sure what was the point.
When you see the insane communities and drive behind projects like PiStorm or Fujinet, makes you wonder.

**Comment by edanuff** [comment]
Hi folks, the A2FPGA core is fully open source and it's easy to use it with boards of your own design.  If you look in the [A2N9 board code](https://github.com/a2fpga/a2fpga_core/tree/main/boards/a2n9), you can see a build of A2FPGA that doesn't depend on the CPLD at all as well as the schematics for the A2N9 board.  The A2N20 board is not open source, so it's not possible at this time for people to manufacture that card themselves but if someone wanted to do the work, they could very easily either use the A2N9 code and schematics as a starting point or use the A2N20 schematics and write their own CPLD code.  The CPLD is fairly trivial in what it does.

For example, here's a picture of development where it's all running on a breadboard with no CPLD at all, just using the code in this repo:

![8A1823C9-F1A9-4AC0-9EE8-574F4E2B9DDF_1_105_c](https://github.com/a2fpga/a2fpga_core/assets/105246/6cdc7f9d-203d-4c6d-a681-3c0f4df04976)
